DELETE http://localhost:3001/api/logout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjBjZEBleGFtcGxlLmNvbSIsImlkIjoxLCJpYXQiOjE3Mzc3MjM2Njh9.iszHlLQKyHl5nMLl6MD-N1fcxteZPdroKSMeQZGcCgI